// <auto-generated />
using System;
using CCommand.CCDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(DatabaseProvider))]
    partial class DatabaseProviderModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("CCommand.CCDatabase.Models.SaveGameManifest", b =>
                {
                    b.Property<Guid>("DatabaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("DatabaseId");

                    b.Property<DateTime>("LastSaved")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastSaved");

                    b.Property<string>("SaveName")
                        .HasColumnType("TEXT")
                        .HasColumnName("SaveName");

                    b.HasKey("DatabaseId");

                    b.ToTable("SaveGameManifest");
                });
#pragma warning restore 612, 618
        }
    }
}
